### ISSUE TITLE
"Table of contents" 한글화

### ISSUE THREAD

**Issue by choonghyunryu** [bit2r/bitPublish#1]
### 현황

- Quarto로 pdf로 book을 생성할 때, 목차를 나타내는 타이틀이 **Table of contents**로 표현됨
- include-before-body: 값을 설정하여 다음과 같이 수정하였음

```
\renewcommand*\figurename{그림}
\renewcommand*\tablename{표}
\renewcommand*\contentsname{목차} 
```

- 그러나 **목차**로 변경되지 않음
- 참고로 **그림과 목차가 Figure와 Table로 출력된 것이 정상적으로 그림과 표로 출력되었음**
  
  ### 원인
  
  - pdf로 조판되기 전에 생성된 Latex 파일에는 사용자가 `include-before-body`로 상기 내용을 재 정의하었지만,
- 정의가 무력화 되었음
- 상기 코드 뒤에 다시 **contentsname**가 재정의되어 있었음

```
begin{document}
\frontmatter
\maketitle
\renewcommand*\figurename{그림}
\renewcommand*\tablename{표}
\renewcommand*\contentsname{목차} 

\ifdefined\Shaded\renewenvironment{Shaded}{\begin{tcolorbox}[enhanced, borderline west={3pt}{0pt}{shadecolor}, frame hidden, boxrule=0pt, interior hidden, breakable, sharp corners]}{\end{tcolorbox}}\fi

\renewcommand*\contentsname{Table of contents}
{
  \hypersetup{linkcolor=}
  \setcounter{tocdepth}{2}
  \tableofcontents
}
```

- **~~아직은 Quarto가 다국어 지원에 미흡한 점이 있음~~**
  
### 문제해결

- `_quarto.yml` 파일과 `include-in-header:`의 역할 분담 정의가 필요해 보임
    -  `_quarto.yml` 파일에서 제공하는 Latex 설정의 범위 파악 필요
- 다음과 같이 `_quarto.yml` 파일의 설정으로 해결

```
format:
  html:
    theme: cosmo
  pdf:
    documentclass: book
    fig-cap-location: bottom
    tbl-cap-location: bottom
    toc-title: "목차"
    crossref: 
      fig-title: "그림"
      tbl-title: "표"
    include-in-header: 
      - file: preamble.tex
    linkcolor: highlight
    urlcolor: highlight
    keep-tex: true
```
