### ISSUE TITLE
cover-image 가 html 출판시 보이지 않습니다.

### ISSUE THREAD

**Issue by statkclee** [bit2r/bitPublish#54]
Quarto Book 에서는 정상작동하지만 bitPublish `cover-image: images/logo.png` 이 반영되지 않습니다.

```
format:
  html:
    theme: cosmo
    cover-image: images/logo.png
```

![image](https://github.com/bit2r/bitPublish/assets/5325425/a5387632-fe74-4ec5-ba4a-711b1bd18390)

**Comment by choonghyunryu** [comment]
@statkclee 

해당 설정을 _extension.yml 파일이 아닌, 다음처럼  _quarto.yml에 지정하면 됩니다.

```
project:
  type: book
  output-dir: docs

lang: ko-KR

book:
  title: "bitPublish를 이용하여 한글 책 조판하기"
  chapters:
    - index.qmd
    - chap_exams.qmd
    - chap_intro_bitpublish.qmd
    - chap_troubleshooting.qmd
    - chap_version.qmd
    - chap_solve_exercise.qmd    
  cover-image: hexlogo/bitPublish_logo.png    
bibliography: references.bib
link-citations: false
```

관련 예제를 적용한 version 0.2.9을 등록했습니다.
참고하시기 바랍니다.
